# 编译环境、语言
dist: xenial
os: linux
language: node_js

# Node.js 版本
node_js:
  - 14

branches:
  only:
    - master                      # 只有 main 分支检出更改才触发 CI

before_install:
  - export TZ='Asia/Shanghai'   # 配置时区为东八区 UTC+8
  - npm install hexo-cli        # 安装 hexo
  - npm install hexo-theme-keep
  - npm install hexo-filter-mathjax

install:
  - npm install                 # 安装 hexo 项目相关的依赖

# 执行脚本 
script:                         
  - hexo clean                  # 清除 hexo 缓存
  - hexo generate               # 生成静态文件
after_script:
  - cd ./public
  - git init
  - git config user.name "xmcchv"   #修改成自己的github用户名
  - git config user.email "1357638634@qq.com"   #修改成自己的GitHub邮箱
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token
deploy:
  on:
    branch: master                # 工作分支
  strategy: git
  provider: pages
  token: $GH_TOKEN              # GitHub Token 变量
  keep_history: true            # 保持推送记录，以增量提交的方式
  local_dir: public             # 需要推送到 gh-pages 分支的静态文件目录
  target_branch: gh-pages       # 推送的目标文件夹 local_dir(public) -> gh-pages 分支
env:
    global:
        - GH_REF: github.com/xmcchv/xmcchv.github.io.git